export const INTERNAL_ERROR_CODES = {
  AUTH_INVALID_SIGNATURE: "INTERNAL_AUTH_INVALID_SIGNATURE",
  AUTH_MISSING: "INTERNAL_AUTH_MISSING",
  AUTH_TIMESTAMP_SKEW: "INTERNAL_AUTH_TIMESTAMP_SKEW",
  SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
